### ISSUE TITLE
Corrección Proyecto. Fase: UT2

### ISSUE THREAD

**Issue by jlr2** [josemariapafo/ProyectoPSP-Grupo3#2]
1. Poner más pequeña la imagen de la portada.
2. Añadir licencia.
3. Poned un título junto con el propio encabezado de cada apartado. Por ejemplo, ponéis "1. Actividad 1 y 2";  añadid un titular del apartado.
4. No entiendo la descripción que hacéis de "logging" en las funcionalidades.

**Comment by scuestam** [comment]
Solucionado
