### ISSUE TITLE
Corrección Proyecto. Fase: UT2. Requisitos técnicos

### ISSUE THREAD

**Issue by jlr2** [josemariapafo/ProyectoPSP-Grupo3#3]
Habéis subido un proyecto que a su vez contiene una carpeta con el proyecto. Poned el código en el raíz de la rama Develop, pliz.
El proyecto hay que hacerlo con IntelliJ (lo entregáis  en Netbeans). Para la próxima entrega revisadlo.

**Comment by josemariapafo** [comment]
Entendido.
